/** Seed-friendly Emerald / Hoenn badge slots. */
export const DEFAULT_BADGE_DEFINITIONS = [
  {
    key: "gym-1",
    label: "Stone Badge",
    category: "gym" as const,
    sortOrder: 1,
    leaderName: "Roxanne",
  },
  {
    key: "gym-2",
    label: "Knuckle Badge",
    category: "gym" as const,
    sortOrder: 2,
    leaderName: "Brawly",
  },
  {
    key: "gym-3",
    label: "Dynamo Badge",
    category: "gym" as const,
    sortOrder: 3,
    leaderName: "Wattson",
  },
  {
    key: "gym-4",
    label: "Heat Badge",
    category: "gym" as const,
    sortOrder: 4,
    leaderName: "Flannery",
  },
  {
    key: "gym-5",
    label: "Balance Badge",
    category: "gym" as const,
    sortOrder: 5,
    leaderName: "Norman",
  },
  {
    key: "gym-6",
    label: "Feather Badge",
    category: "gym" as const,
    sortOrder: 6,
    leaderName: "Winona",
  },
  {
    key: "gym-7",
    label: "Mind Badge",
    category: "gym" as const,
    sortOrder: 7,
    leaderName: "Tate & Liza",
  },
  {
    key: "gym-8",
    label: "Rain Badge",
    category: "gym" as const,
    sortOrder: 8,
    leaderName: "Juan",
  },
  {
    key: "elite-1",
    label: "Elite Four — Sidney",
    category: "elite" as const,
    sortOrder: 9,
    leaderName: "Sidney",
  },
  {
    key: "elite-2",
    label: "Elite Four — Phoebe",
    category: "elite" as const,
    sortOrder: 10,
    leaderName: "Phoebe",
  },
  {
    key: "elite-3",
    label: "Elite Four — Glacia",
    category: "elite" as const,
    sortOrder: 11,
    leaderName: "Glacia",
  },
  {
    key: "elite-4",
    label: "Elite Four — Drake",
    category: "elite" as const,
    sortOrder: 12,
    leaderName: "Drake",
  },
  {
    key: "championship",
    label: "Champion",
    category: "championship" as const,
    sortOrder: 13,
    leaderName: "Wallace",
  },
];

export const POKEMON_TYPES = [
  "Normal",
  "Fighting",
  "Flying",
  "Poison",
  "Ground",
  "Rock",
  "Bug",
  "Ghost",
  "Steel",
  "Fire",
  "Water",
  "Grass",
  "Electric",
  "Psychic",
  "Ice",
  "Dragon",
  "Dark",
  "Fairy",
] as const;
