import assert from "node:assert/strict";
import test from "node:test";
import type { PokemonEntry } from "@/lib/challenge-types";
import type { PokemonType } from "@/lib/pokemon-types";
import {
  getSquadCounterReroll,
  recommendSquadCounters,
} from "@/lib/pokedex-squad-counter";

/** Minimal Main + Reserve squad for counter tip / reroll coverage. */
const squad: PokemonEntry[] = [
  {
    id: "fixture-main-0",
    slot: "MAIN",
    partyIndex: 0,
    nickname: "Muddy",
    species: "Swampert",
    pokedexId: 260,
    isShiny: false,
    types: ["Water", "Ground"] as PokemonType[],
    nature: "Adamant",
    level: 58,
    ability: "Torrent",
    catchRoute: "Littleroot Town (Starter)",
    heldItem: "Leftovers",
    moves: ["Earthquake", "Waterfall", "Ice Beam", "Protect"],
    ivs: null,
    evs: null,
    causeOfDeath: null,
    diedOnRun: null,
    runId: null,
  },
  {
    id: "fixture-main-1",
    slot: "MAIN",
    partyIndex: 1,
    nickname: "Sparky",
    species: "Manectric",
    pokedexId: 310,
    isShiny: false,
    types: ["Electric"] as PokemonType[],
    nature: "Timid",
    level: 54,
    ability: "Static",
    catchRoute: "Route 110",
    heldItem: "Magnet",
    moves: ["Thunderbolt", "Flamethrower", "Thunder Wave", "Crunch"],
    ivs: null,
    evs: null,
    causeOfDeath: null,
    diedOnRun: null,
    runId: null,
  },
  {
    id: "fixture-main-2",
    slot: "MAIN",
    partyIndex: 2,
    nickname: "Raltsie",
    species: "Gardevoir",
    pokedexId: 282,
    isShiny: false,
    types: ["Psychic", "Fairy"] as PokemonType[],
    nature: "Modest",
    level: 55,
    ability: "Synchronize",
    catchRoute: "Route 102",
    heldItem: "Twisted Spoon",
    moves: ["Psychic", "Thunderbolt", "Calm Mind", "Will-O-Wisp"],
    ivs: null,
    evs: null,
    causeOfDeath: null,
    diedOnRun: null,
    runId: null,
  },
  {
    id: "fixture-main-3",
    slot: "MAIN",
    partyIndex: 3,
    nickname: "Shroom",
    species: "Breloom",
    pokedexId: 286,
    isShiny: false,
    types: ["Grass", "Fighting"] as PokemonType[],
    nature: "Jolly",
    level: 52,
    ability: "Effect Spore",
    catchRoute: "Petalburg Woods",
    heldItem: "Miracle Seed",
    moves: ["Spore", "Focus Punch", "Mach Punch", "Rock Tomb"],
    ivs: null,
    evs: null,
    causeOfDeath: null,
    diedOnRun: null,
    runId: null,
  },
  {
    id: "fixture-main-4",
    slot: "MAIN",
    partyIndex: 4,
    nickname: "Iron",
    species: "Aggron",
    pokedexId: 306,
    isShiny: false,
    types: ["Steel", "Rock"] as PokemonType[],
    nature: "Impish",
    level: 53,
    ability: "Sturdy",
    catchRoute: "Granite Cave",
    heldItem: "Sitrus Berry",
    moves: ["Earthquake", "Rock Slide", "Iron Tail", "Roar"],
    ivs: null,
    evs: null,
    causeOfDeath: null,
    diedOnRun: null,
    runId: null,
  },
  {
    id: "fixture-main-5",
    slot: "MAIN",
    partyIndex: 5,
    nickname: "Drake",
    species: "Salamence",
    pokedexId: 373,
    isShiny: true,
    types: ["Dragon", "Flying"] as PokemonType[],
    nature: "Naive",
    level: 56,
    ability: "Intimidate",
    catchRoute: "Meteor Falls",
    heldItem: "Dragon Fang",
    moves: ["Dragon Claw", "Aerial Ace", "Earthquake", "Flamethrower"],
    ivs: null,
    evs: null,
    causeOfDeath: null,
    diedOnRun: null,
    runId: null,
  },
  {
    id: "fixture-reserve-0",
    slot: "RESERVE",
    partyIndex: 0,
    nickname: "Wings",
    species: "Pelipper",
    pokedexId: 279,
    isShiny: false,
    types: ["Water", "Flying"] as PokemonType[],
    nature: "Bold",
    level: 44,
    ability: "Keen Eye",
    catchRoute: "Route 103",
    heldItem: "Mystic Water",
    moves: ["Surf", "Ice Beam", "Toxic", "Protect"],
    ivs: null,
    evs: null,
    causeOfDeath: null,
    diedOnRun: null,
    runId: null,
  },
  {
    id: "fixture-reserve-1",
    slot: "RESERVE",
    partyIndex: 1,
    nickname: "Omen",
    species: "Absol",
    pokedexId: 359,
    isShiny: false,
    types: ["Dark"] as PokemonType[],
    nature: "Adamant",
    level: 46,
    ability: "Pressure",
    catchRoute: "Route 120",
    heldItem: "Black Glasses",
    moves: ["Slash", "Shadow Ball", "Swords Dance", "Aerial Ace"],
    ivs: null,
    evs: null,
    causeOfDeath: null,
    diedOnRun: null,
    runId: null,
  },
  {
    id: "fixture-reserve-2",
    slot: "RESERVE",
    partyIndex: 2,
    nickname: "Clay",
    species: "Claydol",
    pokedexId: 344,
    isShiny: false,
    types: ["Ground", "Psychic"] as PokemonType[],
    nature: "Relaxed",
    level: 48,
    ability: "Levitate",
    catchRoute: "Mirage Tower",
    heldItem: "Chesto Berry",
    moves: ["Earthquake", "Psychic", "Light Screen", "Reflect"],
    ivs: null,
    evs: null,
    causeOfDeath: null,
    diedOnRun: null,
    runId: null,
  },
  {
    id: "fixture-reserve-3",
    slot: "RESERVE",
    partyIndex: 3,
    nickname: "Cloud",
    species: "Altaria",
    pokedexId: 334,
    isShiny: false,
    types: ["Dragon", "Flying"] as PokemonType[],
    nature: "Calm",
    level: 45,
    ability: "Natural Cure",
    catchRoute: "Route 114",
    heldItem: null,
    moves: ["Dragon Dance", "Aerial Ace", "Earthquake", "Sing"],
    ivs: null,
    evs: null,
    causeOfDeath: null,
    diedOnRun: null,
    runId: null,
  },
  {
    id: "fixture-reserve-4",
    slot: "RESERVE",
    partyIndex: 4,
    nickname: "Tusk",
    species: "Walrein",
    pokedexId: 365,
    isShiny: false,
    types: ["Ice", "Water"] as PokemonType[],
    nature: "Quiet",
    level: 47,
    ability: "Thick Fat",
    catchRoute: "Shoal Cave",
    heldItem: "Never-Melt Ice",
    moves: ["Surf", "Ice Beam", "Rest", "Body Slam"],
    ivs: null,
    evs: null,
    causeOfDeath: null,
    diedOnRun: null,
    runId: null,
  },
];

test("does not offer a reroll when the first batch contains every counter", () => {
  const suggestions = recommendSquadCounters(["Water"], squad, { limit: 3 });

  assert.equal(suggestions.length, 2);
  assert.equal(
    getSquadCounterReroll(["Water"], squad, suggestions, [], { limit: 3 }),
    null,
  );
});

test("advances to remaining counters and then offers to restart", () => {
  const first = recommendSquadCounters(["Dragon"], squad, { limit: 3 });
  const more = getSquadCounterReroll(["Dragon"], squad, first, [], {
    limit: 3,
  });

  assert.equal(more?.action, "more");
  assert.deepEqual(
    more?.excludeEntryIds,
    first.map((suggestion) => suggestion.entryId),
  );

  const second = recommendSquadCounters(["Dragon"], squad, {
    excludeEntryIds: more?.excludeEntryIds,
    limit: 3,
  });
  const restart = getSquadCounterReroll(
    ["Dragon"],
    squad,
    second,
    more?.excludeEntryIds ?? [],
    { limit: 3 },
  );

  assert.equal(second.length, 1);
  assert.deepEqual(restart, { action: "restart", excludeEntryIds: [] });
});
