// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non-pooler) connection for advisory locks.
    // Neon pooled URLs time out on pg_advisory_lock during `migrate deploy`.
    url:
      process.env["DATABASE_URL_UNPOOLED"]?.trim() ||
      process.env["DATABASE_URL"],
  },
});
