import type { GuideDocument } from "@/features/guide/guide-types";

/**
 * Emerald / Modern Emerald story spine focused on non-obvious progression gates.
 * Assumed compatible with Modern Emerald unless a season notes otherwise.
 */
export const EMERALD_GUIDE: GuideDocument = {
  id: "emerald",
  gameLabel: "Pokémon Emerald",
  chapters: [
    {
      id: "prologue",
      title: "Littleroot → Petalburg",
      summary: "Starter, early routes, and Dad in Petalburg Gym.",
      requiresBadges: [],
      sortOrder: 0,
    },
    {
      id: "rustboro",
      title: "Rustboro & Cut",
      summary: "Petalburg Woods, Roxanne, and the Cutter’s house.",
      requiresBadges: [],
      clearsWithBadge: "gym-1",
      sortOrder: 1,
    },
    {
      id: "dewford",
      title: "Dewford & Steven",
      summary: "Letter delivery, Granite Cave, Brawly.",
      requiresBadges: ["gym-1"],
      clearsWithBadge: "gym-2",
      sortOrder: 2,
    },
    {
      id: "mauville",
      title: "Slateport → Mauville",
      summary: "Ocean trip, Museum plot, Wattson, Rock Smash house.",
      requiresBadges: ["gym-1", "gym-2"],
      clearsWithBadge: "gym-3",
      sortOrder: 3,
    },
    {
      id: "lavaridge",
      title: "Desert → Lavaridge",
      summary: "Route 111 desert, Mt. Chimney, Flannery.",
      requiresBadges: ["gym-1", "gym-2", "gym-3"],
      clearsWithBadge: "gym-4",
      sortOrder: 4,
    },
    {
      id: "petalburg-gym",
      title: "Petalburg Gym",
      summary: "Norman unlocks after four badges.",
      requiresBadges: ["gym-1", "gym-2", "gym-3", "gym-4"],
      clearsWithBadge: "gym-5",
      sortOrder: 5,
    },
    {
      id: "fortree",
      title: "Fortree & Weather Institute",
      summary: "Surf north, Team Magma/Aqua, Winona.",
      requiresBadges: ["gym-1", "gym-2", "gym-3", "gym-4", "gym-5"],
      clearsWithBadge: "gym-6",
      sortOrder: 6,
    },
    {
      id: "mossdeep",
      title: "Lilycove → Mossdeep",
      summary: "Mt. Pyre, Team hideout, Tate & Liza.",
      requiresBadges: [
        "gym-1",
        "gym-2",
        "gym-3",
        "gym-4",
        "gym-5",
        "gym-6",
      ],
      clearsWithBadge: "gym-7",
      sortOrder: 7,
    },
    {
      id: "sootopolis",
      title: "Seafloor → Sootopolis",
      summary: "Dive, Kyogre/Groudon, Wallace/Juan.",
      requiresBadges: [
        "gym-1",
        "gym-2",
        "gym-3",
        "gym-4",
        "gym-5",
        "gym-6",
        "gym-7",
      ],
      clearsWithBadge: "gym-8",
      sortOrder: 8,
    },
    {
      id: "elite-four",
      title: "Victory Road & League",
      summary: "Ever Grande, Victory Road, Elite Four, Champion.",
      requiresBadges: [
        "gym-1",
        "gym-2",
        "gym-3",
        "gym-4",
        "gym-5",
        "gym-6",
        "gym-7",
        "gym-8",
      ],
      clearsWithBadge: "championship",
      sortOrder: 9,
    },
  ],
  steps: [
    // —— Prologue ——
    {
      id: "prologue-starter",
      chapterId: "prologue",
      title: "Get your starter",
      summary: "Choose Mudkip, Torchic, or Treecko from Prof. Birch on Route 101.",
      detail:
        "After the moving truck cutscene in **Littleroot**, help Birch on **Route 101**. Your starter choice locks your early typing — plan around it for Roxanne (Rock) and Brawly (Fighting).",
      locations: ["Littleroot Town", "Route 101"],
      priority: "critical",
      sortOrder: 10,
    },
    {
      id: "prologue-oldale-petalburg",
      chapterId: "prologue",
      title: "Reach Petalburg and talk to Dad",
      summary: "Visit Petalburg Gym — Norman sends you to Rustboro first.",
      detail:
        "Go through **Oldale** → **Route 102** → **Petalburg City**. Talk to **Norman** in the Gym. He will not battle you until you have **four badges**. He points you toward **Rustboro** via Route 104 / Petalburg Woods.",
      locations: ["Oldale Town", "Route 102", "Petalburg City"],
      requiresSteps: ["prologue-starter"],
      priority: "critical",
      sortOrder: 20,
    },
    {
      id: "prologue-route-104",
      chapterId: "prologue",
      title: "Head toward Rustboro",
      summary: "North on Route 104 into Petalburg Woods, then out to Rustboro.",
      locations: ["Route 104", "Petalburg Woods", "Rustboro City"],
      requiresSteps: ["prologue-oldale-petalburg"],
      priority: "recommended",
      sortOrder: 30,
    },

    // —— Rustboro ——
    {
      id: "rustboro-petalburg-woods",
      chapterId: "rustboro",
      title: "Clear Petalburg Woods",
      summary: "Help the Devon researcher — Magma/Aqua grunts block the north exit.",
      detail:
        "In **Petalburg Woods**, help the Devon employee fight off the Team Magma/Aqua grunt. Afterward you can continue north to **Rustboro City**.",
      locations: ["Petalburg Woods", "Rustboro City"],
      priority: "critical",
      sortOrder: 10,
    },
    {
      id: "rustboro-roxanne",
      chapterId: "rustboro",
      title: "Defeat Roxanne (Stone Badge)",
      summary: "Rustboro Gym — Rock types. Stone Badge unlocks Cut outside battle.",
      detail:
        "**Roxanne** leads with Geodude / Nosepass. Water, Grass, and Fighting hit hard. Earning the **Stone Badge** lets you use **Cut** in the overworld (once you have the HM).",
      locations: ["Rustboro City"],
      autoCompleteWhenBadge: "gym-1",
      nuzlockeNote: "Gym battles are free XP — still respect your level cap.",
      priority: "critical",
      sortOrder: 20,
    },
    {
      id: "rustboro-get-cut",
      chapterId: "rustboro",
      title: "Get Cut from the Cutter’s house",
      summary:
        "House south of the Rustboro Pokémon Center — easy to miss, required for Rusturf.",
      detail:
        "From the **Rustboro Pokémon Center**, go **south one row of houses**. The Cutter’s house is on that street. Talk to the man inside for **HM01 Cut**.\n\nYou need the **Stone Badge** to use Cut outside battle. Cut opens the path into **Rusturf Tunnel** (east of Rustboro via Route 116) later.",
      locations: ["Rustboro City"],
      hms: ["Cut"],
      requiresSteps: ["rustboro-roxanne"],
      priority: "critical",
      sortOrder: 30,
    },
    {
      id: "rustboro-devon-letter",
      chapterId: "rustboro",
      title: "Take the letter from Mr. Stone",
      summary: "Devon Corp president gives you a letter for Steven in Dewford.",
      detail:
        "After the Devon plot in Rustboro (researcher → Devon Corp), speak with **Mr. Stone** upstairs. He gives you a **letter** to deliver to **Steven** in **Dewford**. This is the gate into the Dewford chapter.",
      locations: ["Rustboro City"],
      keyItems: ["Letter"],
      requiresSteps: ["rustboro-roxanne"],
      priority: "critical",
      sortOrder: 40,
    },
    {
      id: "rustboro-to-dewford",
      chapterId: "rustboro",
      title: "Sail to Dewford with Mr. Briney",
      summary: "Cottage on Route 104 (south of Petalburg Woods) — ask Briney for Dewford.",
      detail:
        "Return to **Mr. Briney’s cottage** on the south end of **Route 104** (west of Petalburg Woods’ south exit). With the letter, he will ferry you to **Dewford Town**.",
      locations: ["Route 104", "Dewford Town"],
      requiresSteps: ["rustboro-devon-letter"],
      priority: "critical",
      sortOrder: 50,
    },

    // —— Dewford ——
    {
      id: "dewford-find-steven",
      chapterId: "dewford",
      title: "Find Steven in Granite Cave",
      summary:
        "Granite Cave north of Dewford — go to the lowest floor; he is easy to walk past.",
      detail:
        "From Dewford, go **north** into **Granite Cave**. Descend to the **bottom floor**. **Steven** stands in a side alcove on that floor — talk to him to deliver Mr. Stone’s letter.\n\nBring a Pokémon that can handle Rock types (and Flash later if you want the dark rooms).",
      locations: ["Dewford Town", "Granite Cave"],
      requiresBadges: ["gym-1"],
      keyItems: ["Letter"],
      priority: "critical",
      sortOrder: 10,
    },
    {
      id: "dewford-brawly",
      chapterId: "dewford",
      title: "Defeat Brawly (Knuckle Badge)",
      summary: "Dewford Gym — Fighting types. Knuckle Badge enables Flash.",
      detail:
        "**Brawly** uses Machop / Makuhita. Flying, Psychic, and Ghost are your friends. The **Knuckle Badge** lets you use **Flash** in the overworld.",
      locations: ["Dewford Town"],
      requiresBadges: ["gym-1"],
      autoCompleteWhenBadge: "gym-2",
      priority: "critical",
      sortOrder: 20,
    },
    {
      id: "dewford-to-slateport",
      chapterId: "dewford",
      title: "Sail to Slateport with Briney",
      summary: "After Steven, Briney takes you east to Route 109 / Slateport.",
      detail:
        "Once the letter is delivered, talk to **Mr. Briney** again in Dewford to sail to **Route 109** (beach south of Slateport).",
      locations: ["Dewford Town", "Route 109", "Slateport City"],
      requiresSteps: ["dewford-find-steven"],
      priority: "critical",
      sortOrder: 30,
    },

    // —— Mauville ——
    {
      id: "mauville-slateport-museum",
      chapterId: "mauville",
      title: "Progress the Slateport Museum plot",
      summary: "Team Magma/Aqua at the Museum — then head north to Mauville.",
      detail:
        "In **Slateport**, follow the Team Magma/Aqua scene at the **Oceanic Museum**. Afterward continue **north on Route 110** toward **Mauville City** (bike path / grassy side — your choice).",
      locations: ["Slateport City", "Route 110", "Mauville City"],
      requiresBadges: ["gym-1", "gym-2"],
      priority: "critical",
      sortOrder: 10,
    },
    {
      id: "mauville-wattson",
      chapterId: "mauville",
      title: "Defeat Wattson (Dynamo Badge)",
      summary: "Mauville Gym — Electric. Dynamo Badge unlocks Rock Smash.",
      locations: ["Mauville City"],
      requiresBadges: ["gym-1", "gym-2"],
      autoCompleteWhenBadge: "gym-3",
      priority: "critical",
      sortOrder: 20,
    },
    {
      id: "mauville-rock-smash",
      chapterId: "mauville",
      title: "Get Rock Smash",
      summary: "Mauville house — needed to reopen Rusturf Tunnel toward Verdanturf.",
      detail:
        "In **Mauville**, visit the house where an NPC gives **HM06 Rock Smash** (often pointed out after Wattson’s event). With the **Dynamo Badge**, smash rocks in **Rusturf Tunnel** to open the shortcut to **Verdanturf**.",
      locations: ["Mauville City", "Rusturf Tunnel", "Verdanturf Town"],
      requiresBadges: ["gym-1", "gym-2"],
      hms: ["Rock Smash"],
      requiresSteps: ["mauville-wattson"],
      priority: "critical",
      sortOrder: 30,
    },
    {
      id: "mauville-to-desert",
      chapterId: "mauville",
      title: "Push west toward Fallarbor / Mt. Chimney",
      summary: "Route 111 desert needs Go-Goggles from later — follow the story north-west.",
      detail:
        "From Mauville, the story pulls you toward **Route 111**, **Fallarbor**, and **Mt. Chimney**. You will receive **Go-Goggles** before you can fully cross the desert sands.",
      locations: ["Route 111", "Fallarbor Town", "Mt. Chimney"],
      requiresSteps: ["mauville-wattson"],
      priority: "recommended",
      sortOrder: 40,
    },

    // —— Lavaridge ——
    {
      id: "lavaridge-mt-chimney",
      chapterId: "lavaridge",
      title: "Resolve Mt. Chimney",
      summary: "Cable car up Mt. Chimney — Team Magma/Aqua confrontation.",
      locations: ["Mt. Chimney", "Jagged Pass", "Lavaridge Town"],
      requiresBadges: ["gym-1", "gym-2", "gym-3"],
      priority: "critical",
      sortOrder: 10,
    },
    {
      id: "lavaridge-flannery",
      chapterId: "lavaridge",
      title: "Defeat Flannery (Heat Badge)",
      summary: "Lavaridge Gym — Fire. Heat Badge unlocks Strength.",
      locations: ["Lavaridge Town"],
      autoCompleteWhenBadge: "gym-4",
      priority: "critical",
      sortOrder: 20,
    },
    {
      id: "lavaridge-go-goggles",
      chapterId: "lavaridge",
      title: "Pick up Go-Goggles",
      summary: "Required to cross Route 111 desert toward Fortree later.",
      detail:
        "After the Mt. Chimney events / Flannery arc, make sure you have the **Go-Goggles** from the desert storyline before you need to cross **Route 111**’s sand.",
      locations: ["Route 111", "Lavaridge Town"],
      keyItems: ["Go-Goggles"],
      priority: "critical",
      sortOrder: 30,
    },

    // —— Petalburg Gym ——
    {
      id: "petalburg-norman",
      chapterId: "petalburg-gym",
      title: "Defeat Norman (Balance Badge)",
      summary: "Return to Petalburg Gym — Dad unlocks after four badges.",
      detail:
        "With four badges, **Norman** will finally battle you in **Petalburg Gym**. Normal types — Fighting is ideal. The **Balance Badge** unlocks **Surf** (HM03 from the Petalburg Gym / Wally’s dad chain depending on timing — grab Surf when offered in the Petalburg area / Route 119 story).",
      locations: ["Petalburg City"],
      requiresBadges: ["gym-1", "gym-2", "gym-3", "gym-4"],
      autoCompleteWhenBadge: "gym-5",
      priority: "critical",
      sortOrder: 10,
    },
    {
      id: "petalburg-get-surf",
      chapterId: "petalburg-gym",
      title: "Get Surf",
      summary: "HM03 Surf — required for almost everything after Norman.",
      detail:
        "Obtain **HM03 Surf** from the story rewards around Petalburg / Wally’s family after Norman. Teach it and Surf north from Petalburg / along Route 105–108 toward later areas as needed — most critically, Surf opens **Route 118/119** toward Fortree.",
      locations: ["Petalburg City"],
      hms: ["Surf"],
      requiresSteps: ["petalburg-norman"],
      priority: "critical",
      sortOrder: 20,
    },

    // —— Fortree ——
    {
      id: "fortree-weather-institute",
      chapterId: "fortree",
      title: "Clear the Weather Institute",
      summary: "Route 119 — Team Magma/Aqua; Castform reward; then Fortree.",
      locations: ["Route 119", "Fortree City"],
      requiresBadges: ["gym-1", "gym-2", "gym-3", "gym-4", "gym-5"],
      priority: "critical",
      sortOrder: 10,
    },
    {
      id: "fortree-winona",
      chapterId: "fortree",
      title: "Defeat Winona (Feather Badge)",
      summary: "Fortree Gym — Flying. Feather Badge unlocks Fly.",
      locations: ["Fortree City"],
      autoCompleteWhenBadge: "gym-6",
      priority: "critical",
      sortOrder: 20,
    },
    {
      id: "fortree-get-fly",
      chapterId: "fortree",
      title: "Get Fly",
      summary: "HM02 Fly from Route 119 rival rematch / weather plot rewards.",
      detail:
        "After the Weather Institute events, your rival gives **HM02 Fly** on **Route 119**. You need the **Feather Badge** to use it outdoors.",
      locations: ["Route 119", "Fortree City"],
      hms: ["Fly"],
      requiresSteps: ["fortree-winona"],
      priority: "critical",
      sortOrder: 30,
    },

    // —— Mossdeep ——
    {
      id: "mossdeep-mt-pyre",
      chapterId: "mossdeep",
      title: "Climb Mt. Pyre",
      summary: "Team Magma/Aqua steal the Red/Blue Orb — chase the plot to Lilycove.",
      locations: ["Route 121", "Mt. Pyre", "Lilycove City"],
      priority: "critical",
      sortOrder: 10,
    },
    {
      id: "mossdeep-hideout",
      chapterId: "mossdeep",
      title: "Clear the Team Magma/Aqua hideout",
      summary: "Lilycove harbor hideout — then sail / Surf to Mossdeep.",
      locations: ["Lilycove City", "Route 124", "Mossdeep City"],
      requiresSteps: ["mossdeep-mt-pyre"],
      priority: "critical",
      sortOrder: 20,
    },
    {
      id: "mossdeep-tate-liza",
      chapterId: "mossdeep",
      title: "Defeat Tate & Liza (Mind Badge)",
      summary: "Mossdeep Gym — dual Psychic battle. Mind Badge unlocks Dive.",
      locations: ["Mossdeep City"],
      autoCompleteWhenBadge: "gym-7",
      priority: "critical",
      sortOrder: 30,
    },
    {
      id: "mossdeep-get-dive",
      chapterId: "mossdeep",
      title: "Get Dive",
      summary: "HM08 Dive from Steven’s house in Mossdeep — required for Seafloor Cavern.",
      detail:
        "Visit **Steven’s house** in **Mossdeep** after the gym / space center events to receive **HM08 Dive**. You need the **Mind Badge** to Dive in the overworld. Dark water patches on the routes around Mossdeep lead to **Seafloor Cavern**.",
      locations: ["Mossdeep City"],
      hms: ["Dive"],
      requiresSteps: ["mossdeep-tate-liza"],
      priority: "critical",
      sortOrder: 40,
    },

    // —— Sootopolis ——
    {
      id: "sootopolis-seafloor",
      chapterId: "sootopolis",
      title: "Enter Seafloor Cavern",
      summary: "Dive on Route 128 — confront Team Magma/Aqua and awaken the legendaries.",
      locations: ["Route 128", "Seafloor Cavern"],
      hms: ["Dive"],
      priority: "critical",
      sortOrder: 10,
    },
    {
      id: "sootopolis-cave-of-origin",
      chapterId: "sootopolis",
      title: "Calm Sootopolis (Cave of Origin)",
      summary: "Meet Wallace/Juan and stop Kyogre/Groudon in Cave of Origin.",
      locations: ["Sootopolis City", "Cave of Origin"],
      requiresSteps: ["sootopolis-seafloor"],
      priority: "critical",
      sortOrder: 20,
    },
    {
      id: "sootopolis-juan",
      chapterId: "sootopolis",
      title: "Defeat Juan / Wallace (Rain Badge)",
      summary: "Sootopolis Gym — Water. Rain Badge unlocks Waterfall.",
      locations: ["Sootopolis City"],
      autoCompleteWhenBadge: "gym-8",
      priority: "critical",
      sortOrder: 30,
    },
    {
      id: "sootopolis-waterfall",
      chapterId: "sootopolis",
      title: "Get Waterfall",
      summary: "HM07 Waterfall — needed for Victory Road’s water climbs.",
      detail:
        "After the Rain Badge, obtain **HM07 Waterfall** (story gift in the Sootopolis / Wallace chain) before tackling **Victory Road**.",
      locations: ["Sootopolis City", "Ever Grande City", "Victory Road"],
      hms: ["Waterfall"],
      requiresSteps: ["sootopolis-juan"],
      priority: "critical",
      sortOrder: 40,
    },

    // —— Elite Four ——
    {
      id: "e4-victory-road",
      chapterId: "elite-four",
      title: "Clear Victory Road",
      summary: "Ever Grande — Strength, Rock Smash, Waterfall, and Surf puzzles.",
      locations: ["Ever Grande City", "Victory Road"],
      hms: ["Strength", "Rock Smash", "Waterfall", "Surf"],
      priority: "critical",
      sortOrder: 10,
    },
    {
      id: "e4-league",
      chapterId: "elite-four",
      title: "Beat the Elite Four & Champion",
      summary: "Sidney → Phoebe → Glacia → Drake → Wallace (Champion).",
      detail:
        "Prepare a balanced party. You heal between Elite Four members only if you leave — treat it as one long gauntlet. Mark **Championship** on your board when Wallace falls.",
      locations: ["Ever Grande City"],
      autoCompleteWhenBadge: "championship",
      priority: "critical",
      sortOrder: 20,
    },
  ],
};
