/**
 * Modern Emerald catch-route catalog.
 *
 * Generated by `npm run data:catch-routes` from the ROM's own tables — the
 * `NuzlockeLUT` area list, the wild-encounter tables, and the region-map names.
 * Edit the generator, not this file's data.
 *
 * Not every catalog row is a route you can claim. A player can legitimately log
 * a fossil revive at Rustboro or Latios at Southern Island, so those labels stay
 * searchable, but they are not open-route slots — `countsTowardOpen` is the only
 * thing the open/claimed views should filter on.
 */
import {
  CATCH_ROUTE_ROWS,
  NUZLOCKE_AREA_COUNT,
} from "@/data/catch-routes.generated";

export type CatchRouteKind =
  /** Has a wild encounter table — a real nuzlocke route slot. */
  | "wild"
  /** No wild table; only a gift, fossil, trade or `seteventmon` legendary. */
  | "static"
  /** No wild table and no script source: reachable only by hatching an egg there. */
  | "egg-only"
  /** The mapsec exists but no map carries it (e.g. Mirage Island is a Route 130 layout swap). */
  | "unreachable"
  /** Umbrella label kept so pre-split imports and free text keep resolving. */
  | "legacy"
  /** `METLOC_*` sentinel rather than a place. */
  | "pseudo";

export type CatchRouteEncounter =
  | "land"
  | "water"
  | "rock-smash"
  | "fishing"
  /** Scripted catch (`setwildbattle` / `givemon` / `seteventmon`), e.g. New Mauville Voltorbs. */
  | "static";

export type CatchRouteClaimSource =
  /** Claimable from a Pokémon's met location and from the nuzlocke encounter flags. */
  | "both"
  /** Flags only — the mapsec is synthesized at runtime and never stamped on a Pokémon. */
  | "encounter-flag"
  /** Met location only — the ROM does not track this area. */
  | "met-location"
  | "none";

export type CatchRoute = {
  /** Additional strings that resolve to this row (old labels, free text). */
  aliases: readonly string[];
  /**
   * Real wild encounters but no `NuzlockeLUT` bit. The ROM's LUT is a
   * designated-initializer array with no sentinel, so these share Route 101's
   * flag in game — catching here can lock Route 101 out.
   */
  aliasesRoute101?: boolean;
  claimSource: CatchRouteClaimSource;
  /** The only field the open/claimed route views should filter on. */
  countsTowardOpen: boolean;
  encounters: readonly CatchRouteEncounter[];
  kind: CatchRouteKind;
  label: string;
  /** Modern Emerald MAPSEC ids that resolve to this label. */
  mapsecs: readonly number[];
  /** `NuzlockeEncounterFlags` bit index, or null when the ROM does not track it. */
  nuzlockeBit: number | null;
  /**
   * The in-game encounter slot this row consumes. Rows sharing a slotKey are one
   * slot — catching on any of them spends it for all. Null when the row is not
   * an encounter slot at all.
   */
  slotKey: number | null;
};

/** Assignment, not a cast: it typechecks the generated rows against CatchRoute. */
export const CATCH_ROUTE_TABLE: readonly CatchRoute[] = CATCH_ROUTE_ROWS;

export { NUZLOCKE_AREA_COUNT };

/** Every label, in game order. This is the searchable picker list. */
export const CATCH_ROUTES: readonly string[] = CATCH_ROUTE_TABLE.map(
  (route) => route.label,
);

/** Labels a wild catch can actually claim — the open-routes denominator. */
export const OPEN_CATCH_ROUTES: readonly string[] = CATCH_ROUTE_TABLE.filter(
  (route) => route.countsTowardOpen,
).map((route) => route.label);

export function normalizeCatchRoute(route: string): string {
  return route.trim().toLowerCase();
}

const ROUTE_BY_KEY = new Map<string, CatchRoute>();
for (const route of CATCH_ROUTE_TABLE) {
  ROUTE_BY_KEY.set(normalizeCatchRoute(route.label), route);
  for (const alias of route.aliases) {
    const key = normalizeCatchRoute(alias);
    if (!ROUTE_BY_KEY.has(key)) ROUTE_BY_KEY.set(key, route);
  }
}

/** Resolve a stored `catchRoute` string (label or alias) to its catalog row. */
export function findCatchRoute(route: string | null | undefined): CatchRoute | null {
  if (!route?.trim()) return null;
  return ROUTE_BY_KEY.get(normalizeCatchRoute(route)) ?? null;
}

/**
 * Outdoor mapsecs with no wild encounter table — walking there never rolls a
 * grass/surf/fish/rock-smash encounter, so hatching an egg won't burn a wild
 * route slot. Indoors (Centers, houses, marts) are always safe too; those are
 * not catalog rows.
 *
 * `egg-only` = no wild table and no script static. `static` with empty
 * `encounters` = gifts/fossils/legendaries may live here, but outdoor tiles
 * still have no wild table.
 */
export function isHatchSafeOutdoor(route: CatchRoute): boolean {
  return (
    route.kind === "egg-only" ||
    (route.kind === "static" && route.encounters.length === 0)
  );
}

/** Canonical outdoor hatch-safe labels, in catalog order. */
export const HATCH_SAFE_OUTDOOR_ROUTES: readonly string[] = CATCH_ROUTE_TABLE.filter(
  isHatchSafeOutdoor,
).map((route) => route.label);

/**
 * Town/city labels that still have wild tables (usually water/fishing). Look
 * hatch-safe on a map but outdoor walking can still consume a slot — prefer a
 * Center or a true hatch-safe outdoor label instead.
 */
export const HATCH_FALSE_FRIEND_ROUTES: readonly string[] = CATCH_ROUTE_TABLE.filter(
  (route) =>
    route.kind === "wild" &&
    route.encounters.length > 0 &&
    /(?:Town|City)$/.test(route.label),
).map((route) => route.label);

/**
 * Aliases are searchable too, so a player typing a label we have since renamed
 * ("Starter gift") still finds its row — the canonical label is what they pick.
 */
export function searchCatchRoutes(query: string, limit = 40): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return CATCH_ROUTES.slice(0, limit);
  return CATCH_ROUTE_TABLE.filter(
    (route) =>
      route.label.toLowerCase().includes(q) ||
      route.aliases.some((alias) => alias.toLowerCase().includes(q)),
  )
    .slice(0, limit)
    .map((route) => route.label);
}
