/**
 * Modern Emerald item catalog — what an item does, and everywhere the ROM puts
 * one.
 *
 * Generated by `npm run data:items` from the ROM's own tables (`gItems`, the
 * map item balls / hidden items / mart stock, `species_info.h` wild holds, the
 * Pickup tables, and the initial berry planting). Edit the generator, not
 * `items.generated.ts`.
 *
 * Two things about this data that the UI has to respect:
 *
 * 1. **Item locations are not randomized.** `tx_Random_Items` exists as a save
 *    bit but `IsRandomItemsActivated` has no callers anywhere in the ROM, so a
 *    ball on Route 110 is a ball on Route 110 in every seed. What *does* move is
 *    the species holding an item — `SetWildMonHeldItem` reads the species after
 *    `CreateWildMon` has already rerolled it, so a `held` source means "whatever
 *    route that species landed on in your seed", not a vanilla route.
 * 2. **`sources` is ordered fixed-location first.** A place you can walk to
 *    beats a probability, and four evolution items (Spell Tag, Metal Coat,
 *    Dragon Scale, Up-Grade) have no fixed location at all.
 */
import { itemKey } from "@/data/item-links";
import { ITEM_ROWS } from "@/data/items.generated";
import speciesEvolutionsData from "@/data/species-evolutions.json";
import { findPokemonById } from "@/data/pokemon-index";
import type { EvolutionEdgeRaw } from "@/lib/species-evolutions";

export type ItemPocket = "items" | "balls" | "tm-hm" | "berries" | "key";

export type ItemSourceKind =
  /** Visible Poké Ball on the overworld. */
  | "ball"
  /** Itemfinder / hidden square. */
  | "hidden"
  /** Handed over by an NPC script (`giveitem`). */
  | "gift"
  /** Berry tree planted at new game. */
  | "berry"
  /** Sold in a shop. */
  | "mart"
  /** Held by a wild species — moves with the seed, unlike every kind above. */
  | "held"
  /** Pickup ability roll. */
  | "pickup";

/** `common` / `rare` for a rarity roll; `always` when the ROM's 100% idiom applies. */
export type ItemSourceRate = "common" | "rare" | "always";

export type ItemSource = {
  kind: ItemSourceKind;
  /** Catch-route vocabulary label (map sources only). */
  where?: string;
  /** The specific map, when it differs from the region label. */
  detail?: string;
  /** Holder species display name (`held` only). */
  species?: string;
  /** Holder National Dex id, when the catalog knows the species. */
  pokedexId?: number;
  rate?: ItemSourceRate;
  /** Repeats of an otherwise identical source (three balls on one route). */
  count?: number;
};

export type ModernItem = {
  slug: string;
  name: string;
  /** TM/HM only — the move it teaches. */
  move?: string;
  price: number;
  pocket: ItemPocket;
  description: string;
  sources: readonly ItemSource[];
};

export const ITEM_TABLE: readonly ModernItem[] = ITEM_ROWS as readonly ModernItem[];

/**
 * Wild hold rates from `SetWildMonHeldItem` (src/pokemon.c). Not the vanilla
 * 50/45/5 — this ROM rolls 45/45/10, which roughly doubles the odds on the
 * items that have no other source.
 */
export const WILD_HOLD_RATES = {
  none: 45,
  common: 45,
  rare: 10,
  /** A lead with Compound Eyes shifts the same roll to 20/60/20. */
  compoundEyes: { none: 20, common: 60, rare: 20 },
} as const;

const ITEM_BY_KEY = new Map<string, ModernItem>();
for (const item of ITEM_TABLE) {
  ITEM_BY_KEY.set(itemKey(item.slug), item);
  // Display names lose to slugs: "TM03" would otherwise shadow tm-water-pulse.
  const nameKey = itemKey(item.name);
  if (!ITEM_BY_KEY.has(nameKey)) ITEM_BY_KEY.set(nameKey, item);
}

export function findItem(
  nameOrSlug: string | null | undefined,
): ModernItem | null {
  if (!nameOrSlug?.trim()) return null;
  return ITEM_BY_KEY.get(itemKey(nameOrSlug)) ?? null;
}

export type ItemEvolutionUse = {
  /** Species that consumes the item. */
  fromId: number;
  fromName: string;
  intoId: number;
  intoName: string;
  method: string;
  /** `EVO_TRADE_ITEM` — needs a partner, not just the item. */
  needsTrade: boolean;
  /** `EVO_ITEM_HOLD*` — hold it and level, rather than using it from the bag. */
  isHold: boolean;
};

const BY_DEX = (
  speciesEvolutionsData as { byDex: Record<string, EvolutionEdgeRaw[]> }
).byDex;

function speciesName(pokedexId: number): string {
  return findPokemonById(pokedexId)?.name ?? `#${pokedexId}`;
}

/** item key → evolutions it gates, built once from the ROM evolution graph. */
const EVOLUTION_USES_BY_ITEM = new Map<string, ItemEvolutionUse[]>();
for (const [fromKey, edges] of Object.entries(BY_DEX)) {
  const fromId = Number(fromKey);
  for (const edge of edges) {
    if (edge.paramKind !== "item") continue;
    const key = itemKey(String(edge.param));
    const list = EVOLUTION_USES_BY_ITEM.get(key) ?? [];
    list.push({
      fromId,
      fromName: speciesName(fromId),
      intoId: edge.into,
      intoName: speciesName(edge.into),
      method: edge.method,
      needsTrade: edge.method === "EVO_TRADE_ITEM",
      isHold: edge.method.startsWith("EVO_ITEM_HOLD"),
    });
    EVOLUTION_USES_BY_ITEM.set(key, list);
  }
}
for (const list of EVOLUTION_USES_BY_ITEM.values()) {
  list.sort((a, b) => a.fromName.localeCompare(b.fromName));
}

export function evolutionUsesForItem(
  nameOrSlug: string | null | undefined,
): ItemEvolutionUse[] {
  const item = findItem(nameOrSlug);
  if (!item) return [];
  return EVOLUTION_USES_BY_ITEM.get(itemKey(item.slug)) ?? [];
}

/** Slugs of every item that gates at least one evolution in this ROM. */
const EVOLUTION_ITEM_SLUGS: ReadonlySet<string> = new Set(
  ITEM_TABLE.filter(
    (item) => (EVOLUTION_USES_BY_ITEM.get(itemKey(item.slug))?.length ?? 0) > 0,
  ).map((item) => item.slug),
);

/**
 * Directory lenses. `useful` is the default: the long tail of the bag (61 key
 * items, 58 TMs, every Mail) buries the ~30 items anyone is actually hunting.
 */
export type ItemLens = "useful" | "evolution" | "held" | "all";

export const ITEM_LENSES: ReadonlyArray<{ id: ItemLens; label: string }> = [
  { id: "useful", label: "Worth hunting" },
  { id: "evolution", label: "Evolution" },
  { id: "held", label: "Held" },
  { id: "all", label: "All items" },
];

export function parseItemLens(raw: string | null | undefined): ItemLens {
  if (raw === "evolution" || raw === "held" || raw === "all") return raw;
  return "useful";
}

/** True when a wild species can be found holding this item. */
function hasWildHolder(item: ModernItem): boolean {
  return item.sources.some((source) => source.kind === "held");
}

/**
 * The uncomfortable case this tool exists for: an item with no fixed pickup
 * anywhere, obtainable only off a wild holder whose route depends on the seed.
 */
export function isWildHoldOnly(item: ModernItem): boolean {
  if (item.sources.length === 0) return false;
  return item.sources.every(
    (source) => source.kind === "held" || source.kind === "pickup",
  );
}

function matchesLens(item: ModernItem, lens: ItemLens): boolean {
  switch (lens) {
    case "evolution":
      return EVOLUTION_ITEM_SLUGS.has(item.slug);
    case "held":
      return hasWildHolder(item);
    case "all":
      return true;
    case "useful":
      // Key items are plot; Mail is decoration. Everything else in the bag can
      // plausibly matter to a run, including TMs and balls.
      return (
        item.pocket !== "key" &&
        !/ mail$/i.test(item.name) &&
        (item.sources.length > 0 || EVOLUTION_ITEM_SLUGS.has(item.slug))
      );
  }
}

export function searchItems(
  query: string,
  options?: { lens?: ItemLens; limit?: number },
): ModernItem[] {
  const lens = options?.lens ?? "useful";
  const q = query.trim().toLowerCase();
  const hits = ITEM_TABLE.filter((item) => {
    if (!matchesLens(item, lens)) return false;
    if (!q) return true;
    return (
      item.name.toLowerCase().includes(q) ||
      item.slug.includes(q.replace(/\s+/g, "-")) ||
      (item.move?.toLowerCase().includes(q) ?? false) ||
      item.sources.some(
        (source) =>
          source.where?.toLowerCase().includes(q) ||
          source.species?.toLowerCase().includes(q),
      )
    );
  });
  // Evolution items first — they are why anyone opens this tool — then by name.
  hits.sort((a, b) => {
    const evoDelta =
      Number(EVOLUTION_ITEM_SLUGS.has(b.slug)) -
      Number(EVOLUTION_ITEM_SLUGS.has(a.slug));
    if (evoDelta !== 0) return evoDelta;
    return a.name.localeCompare(b.name);
  });
  return options?.limit == null ? hits : hits.slice(0, options.limit);
}
